### ISSUE TITLE
 invalidQuery: Syntax error: Expected ")" but got ":"

### ISSUE THREAD

**Issue by ghost** [Cold-Bore-Capital/looker_period_control#11]
Using BigQuery data warehouse and noticed that the Days In Period metric does not work. Looking at the main.view file, it seems like you're using the :: to cast the field rather than the BigQuery support cast( X as Y) syntax. I've also confirmed the manifest is using the correct database type constant.

![manifest](https://github.com/Cold-Bore-Capital/looker_period_control/assets/132005276/842fe8ad-4ed6-4cfa-9bee-31fd540df901)

![Without_Days_In_Period](https://github.com/Cold-Bore-Capital/looker_period_control/assets/132005276/5f4b5637-a277-4021-9c39-5ddd887b258f)

![With_Days_In_Period](https://github.com/Cold-Bore-Capital/looker_period_control/assets/132005276/8fc63490-7468-4c98-988f-f8517b372404)

![Looker_PoP__Error](https://github.com/Cold-Bore-Capital/looker_period_control/assets/132005276/06208c56-8341-49d5-891a-2b52d3b435ea)

Error Message: 
invalidQuery: Syntax error: Expected ")" but got ":" at [32:15]

**Comment by coldborecapital** [comment]
Give the new version [v1.1.6](https://github.com/Cold-Bore-Capital/looker_period_control/releases/tag/v1.1.6) a try.
