### ISSUE TITLE
date_add is not a valid Snowflake function

### ISSUE THREAD

**Issue by jonathandufault89** [Cold-Bore-Capital/looker_period_control#12]
The function is `dateadd(<part>, <value>, <expression>)` which is causing issue (tested in v1.1.6)

**Comment by coldborecapital** [comment]
This should be fixed in version 1.1.7  (9e3be88e511df3366d433afb971c6414c1b2554e). I changed all Snowflake instances of date_add to dateadd and date_diff to datediff.

**Comment by coldborecapital** [comment]
I just realized I have one more change to make. I will release v1.1.8 shortly.

**Comment by fdawans** [comment]
For BQ, the function is `date_add` - it seems to be broken now (maybe that's fixed in 1.1.8).
https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_add

**Comment by coldborecapital** [comment]
@fdawans , I do not see an error in by BigQuery test pattern. Can you send me an output of the failing SQL? I checked, and all the BigQuery date_add functions seem to be in the right format.

**Comment by fdawans** [comment]
OK, my bad... I forgot a step in the setup.
Had to switch to BigQuery & convert my timestamp to make it work.
Thank you!

**Comment by coldborecapital** [comment]
Note that I was wrong about there being a problem with 1.1.7. Looker was just freaking out for some unknown reason. Everything started working again after forcing it to update dependencies. I'm going to hold on v1.1.7 for now. 

I will release the V2 branch at some point in the future, but I'm just slammed on other projects and haven't had time to fully run the testing to ground.
