### ISSUE TITLE
Issues with display dates in period labels on BigQuery

### ISSUE THREAD

**Issue by fdawans** [Cold-Bore-Capital/looker_period_control#13]
Hello,
The functionality does not seem to be working as expected.
I might have made a mistake somewhere in the setup.
Thank you for your help,

<img width="1507" alt="image" src="https://github.com/Cold-Bore-Capital/looker_period_control/assets/53601011/d3fceefe-65d7-432d-b14a-081215b035e3">

**Comment by coldborecapital** [comment]
You probably need to add the following constant override 

```  
override_constant: date_display_format {
    value: "%b-%d-%Y"
  }
```

Your block should look something like this

```
remote_dependency: looker_period_control {
  project: "looker_period_control"
  override_constant: database_type {
    value: "bigquery"
  }
  override_constant: date_display_format {
    value: "%b-%d-%Y"
  }
}
```

If that doesn't solve the problem, please post the remote dependency portion of your manifest.

**Comment by fdawans** [comment]
Thank you, it's working now!
I must have missed it.
