### ISSUE TITLE
Error while installing it on localized poject

### ISSUE THREAD

**Issue by jcvegan** [Cold-Bore-Capital/looker_period_control#14]
Hi all, first thanks you for this effort. 
Right now, we are trying to implement this on our project. But we are facing this problem:

Our project is localized, so when adding the `remote_dependecy` to the manifest, we are getting this error:
`This project is localized and cannot import project looker_period_control.`

![image](https://github.com/Cold-Bore-Capital/looker_period_control/assets/5739222/e6331541-be42-427c-9225-c13c8f1ee967)

Do you know a way to get rid of this error?

Again, thank you

**Comment by coldborecapital** [comment]
I'm not familiar with localized installs, but I imagine you could just copy the code directly into a local project and then use a local dependency. That's how I run the project when I'm developing. That would look something like this (make sure to change the options to the DB system you're using):

```
local_dependency: {
  project: "looker_period_control"
  override_constant: database_type {
    value: "bigquery"
  }
  override_constant: date_display_format {
    value: "%b-%d-%Y"
  }
}
```

**Comment by jcvegan** [comment]
Hi @coldborecapital , actually that'a a good suggestion.

Thanks, will try.
